# Generated by Django 5.1.6 on 2025-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationAndTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('trining', 'Trining'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('ssc', 'Ssc'), ('hsc', 'Hsc'), ('bsc', 'Bsc')], max_length=50)),
                ('institution_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
    ]
