# Generated by Django 5.1.6 on 2025-02-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_skillcategory_myskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=6)),
                ('project_type', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='project_logos/')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=11)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
