# Generated by Django 5.1.6 on 2025-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_website_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('on_holiday', 'On Holiday')], default='available', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('short_intro', models.TextField(max_length=500)),
                ('company_name', models.CharField(max_length=200)),
                ('hireme_link', models.URLField(max_length=500)),
                ('download_cv_button', models.URLField(max_length=500)),
                ('long_biography', models.TextField()),
            ],
        ),
    ]
