# Generated by Django 5.1.6 on 2025-02-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_heroinfo_download_cv_button_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('small_talk', models.TextField()),
                ('hire_me_link', models.URLField()),
                ('contact_me_link', models.URLField(help_text='Upload like contact')),
                ('copyright_text', models.CharField(max_length=255)),
            ],
        ),
    ]
