# Generated by Django 5.1.6 on 2025-02-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_footer_contact_me_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='contact_me_link',
        ),
    ]
