# Generated by Django 5.1.6 on 2025-02-11 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_footer_contact_me_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='social_icons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
                ('icon_link', models.URLField()),
            ],
        ),
    ]
