# Generated by Django 5.1.6 on 2025-02-11 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_socialicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='icon',
            field=models.FileField(help_text='Upload an SVG file', upload_to='static/icon/'),
        ),
        migrations.AlterField(
            model_name='socialicon',
            name='icon',
            field=models.FileField(upload_to='static/icon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])]),
        ),
        migrations.AlterField(
            model_name='website',
            name='favicon',
            field=models.FileField(blank=True, help_text='Upload an SVG file', null=True, upload_to='static/icon/'),
        ),
        migrations.AlterField(
            model_name='website',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
    ]
