# Generated by Django 6.0.1 on 2026-01-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_myproject_logo_alter_myskill_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='MailjetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Mailjet API Key', max_length=255)),
                ('api_secret', models.CharField(help_text='Mailjet API Secret', max_length=255)),
                ('admin_email', models.EmailField(help_text='Admin email to receive contact form submissions', max_length=254)),
                ('sender_email', models.EmailField(help_text='Sender email address', max_length=254)),
                ('sender_name', models.CharField(default='Portfolio Contact Form', help_text='Sender name', max_length=100)),
            ],
            options={
                'verbose_name': 'Mailjet Settings',
                'verbose_name_plural': 'Mailjet Settings',
            },
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='availability',
            field=models.CharField(choices=[('available', 'Available Now'), ('on_holiday', 'On Holiday')], default='available', max_length=20),
        ),
    ]
