# Generated by Django 5.2.10 on 2026-01-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_contactsubmission_mailjetsettings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='website',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='heroinfo',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for hero section', null=True, upload_to='static/image/'),
        ),
    ]
