# Generated by Django 5.2.10 on 2026-01-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_remove_website_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(blank=True, default='Portfolio', max_length=100),
        ),
    ]
