# Generated by Django 5.2.10 on 2026-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_website_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationandtraining',
            name='status',
            field=models.CharField(default='Completed', help_text='Enter status like: Running, Completed, CGPA, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='myskill',
            name='icon',
            field=models.FileField(blank=True, help_text='Upload an SVG file', null=True, upload_to='static/icon/'),
        ),
    ]
