# Generated by Django 5.2.10 on 2026-01-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_educationandtraining_status_alter_myskill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationandtraining',
            name='vpd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter VPD if status is VPD', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='educationandtraining',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter CGPA if status is CGPA', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='educationandtraining',
            name='status',
            field=models.CharField(default='Completed', help_text='Enter status: Running, Completed, CGPA, or VPD', max_length=50),
        ),
    ]
