# Generated by Django 5.2.10 on 2026-01-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_educationandtraining_vpd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationandtraining',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter GPA if status is GPA', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='educationandtraining',
            name='status',
            field=models.CharField(default='Completed', help_text='Enter status: Running, Completed, CGPA, VPD, or GPA', max_length=50),
        ),
    ]
