# Generated by Django 5.2.10 on 2026-01-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_educationandtraining_gpa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationandtraining',
            name='training_type',
            field=models.CharField(max_length=50),
        ),
    ]
